<a href="https://colab.research.google.com/github/pritamAgrawal9/machine-learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import numpy as np
import matplotlib.pyplot as plt


In [96]:
lst = [1, 2, 3, 4]
arr = np.array(lst)
arr.ndim

1

In [ ]:
type(arr)
arr.shape

(4,)

In [90]:
ls1 = [1, 2, 3, 4, 5]
ls2 = [2, 3, 4, 5, 6]
ls3 = [3, 4, 5, 6, 7]
p = np.array([ls1, ls2, ls3])
p.shape

(3, 5)

In [9]:
import numpy as np

In [12]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
arr.shape

(5,)

In [72]:
ls1 = [1, 2, 3, 4]
ls2 = [2, 3, 4, 5]
ls3 = [3, 4, 5, 6]
ls4 = [4, 5, 6, 7]
ar2 = np.array([ls1, ls2, ls3])
ar2.ndim

2

In [60]:
ar3 = np.ones((4, 2))
type(ar3[1])

numpy.ndarray

In [79]:
do = [0, 0, 0]
d = np.array([[[do,do,do],[do,do,do]]])
d

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [36]:
ar2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [46]:
ar2[1:,3:]

array([[5, 6],
       [6, 7]])

In [48]:
ar2[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [68]:
ar4 = np.arange(1,25).reshape(2, 3, 4)
ar4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [98]:
do = [0, 0, 0]
d = np.array([[do,do,do],[do,do,do]])
d.ndim

3

In [95]:
ls1 = [1, 2, 3, 4]
ls2 = [2, 3, 4, 5]
ls3 = [3, 4, 5, 6]
ls4 = [4, 5, 6, 7]
ar4 = np.arange(1,17).reshape(4,4)
ar4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [97]:
arr1 = np.array([1, 2, 3])
arr1.ndim

1

In [102]:
ls1 = [1, 2, 3, 4]
ls2 = [2, 3, 4, 5]
ls3 = [3, 4, 5, 6]

arr1 = np.array([ls1, ls2, ls3])
arr2 = np.array(ls2)

result = arr1 + arr2
result

array([[ 3,  5,  7,  9],
       [ 4,  6,  8, 10],
       [ 5,  7,  9, 11]])

In [103]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.dot(arr1, arr2)
result

array([[19, 22],
       [43, 50]])

In [108]:
men = np.arange(1,21)
mean= np.mean(men)
print(f'mean = {mean}')
std = np.std(men)
print(f'standard deviation = {std}')


mean = 10.5
standard deviation = 5.766281297335398
